name: users_pagination_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_spinkit: ^5.2.2
  fpdart: ^1.2.0
  get_it: ^8.2.0
  go_router: ^16.3.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  logger: ^2.6.2
  skeletonizer: ^2.1.0+1

dev_dependencies:
  build_runner: 2.10.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  hive_ce_generator: 1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
