// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:users_pagination_task/app/features/user_list/data/models/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressAdapter());
    registerAdapter(BankAdapter());
    registerAdapter(CompanyAdapter());
    registerAdapter(CoordinatesAdapter());
    registerAdapter(CryptoAdapter());
    registerAdapter(HairAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressAdapter());
    registerAdapter(BankAdapter());
    registerAdapter(CompanyAdapter());
    registerAdapter(CoordinatesAdapter());
    registerAdapter(CryptoAdapter());
    registerAdapter(HairAdapter());
    registerAdapter(UserModelAdapter());
  }
}
